### ISSUE TITLE
Empty ladder (to be filled in) appears step by step

### ISSUE THREAD

**Issue by jsms90** [CYPIAPT-LNDSE/anxiety-ladder#22]
As a young person suffering from anxiety
I want to create individual steps for each ladder
So that I have actionable steps to focus on and review

+ [x] Create structure for content within each step i.e. Description of challenge, anxiety rating (slider) and '+' for next step
+ [x] Style each step to look like part of a ladder #37 
+ [x] Create cloud at the top of the page, for the ladder to fold from #26
+ [x] Add animation for each new rung folding down #27

**Comment by SavageWilliam** [comment]
@jsms90 I'm currently working on checklist item 2
